### PR TITLE
add defaults to help with branding

### PR DESCRIPTION
**Pull request by clemenko**
**What this PR does / why we need it**:
This change to the default values allows someone to easily change titles.

**Which issue(s) this PR fixes**:

### CODE REVIEW

**Comment by jggoebel** [comment]
Looks good. 
However sometimes we need the admin-ui and ui title to be different. We should leave this the way it was

**Comment by clemenko** [comment]
help me understand when the scenario calls for different titles?

**Comment by jggoebel** [comment]
When i have multiple tabs open it may be easier if one of the Tabs is called "HobbyFarm Administration", so i can distinguish between the administration and the user interface. 

On the other hand we sometimes have multiple instances of HobbyFarm (for testing, or branded for some purpose) we do sometimes not want the user to see this (so all users will see "HobbyFarm" , but in the admin ui it should also be distuingishable without looking at the URL that this is instance 2 or 3. "HobbyFarm i2" or "HobbyFarm Projekt X" (So we do not confuse two instances and set some wrong settings in production etc.)

**Comment by clemenko** [comment]
Understandable. I added back the admin-ui.title field.

**Comment by jggoebel** [comment]
Thanks!

**Comment by clemenko** [comment]
Who is able to merge? RGS is looking to starting using HF heavily.

**Comment by jggoebel** [comment]
@ebauman and i am able to merge this.
However this changes have no effect until a new Chart is being released.
Next release is scheduled for the end of september. So we will merge it before that new release. Is that fine with you?

**Comment by clemenko** [comment]
Any chance of getting it sooner? We have workshops planned for august.

**Comment by jggoebel** [comment]
I mean you could deploy it right now with the current release 3.0 and use the old value structure, right?

**Comment by clemenko** [comment]
But then we don't have the updated logos. We can zip up the new chart and share it if you don't want to update the chart before the software.

**Comment by jggoebel** [comment]
The only problem i have with merging this right now that it breaks old values files for people that have HF installed. we do not want to to this without changing the major version, which will happen at the end of september. we just released 3.0 one or two weeks ago

**Comment by jggoebel** [comment]
Are the logos not working for you guys? We have setup a hobbyfarm instance with all logos configured right now for the current chart version

**Comment by jggoebel** [comment]
You will just have to provide a URL to the logo

**Comment by clemenko** [comment]
It doesn't really break anything. With the current chart URLS do not work. You have to add your own configmap. And mount to the image. That is part of the chart update here. 

Wait, Where is the URL piece documented?

**Comment by jggoebel** [comment]
URLs do work. we have that set up...
ehm where that is documented i am unsure about that. maybe it is not?

**Comment by clemenko** [comment]
Not documented AND requires a web server.. I like the configmap way. :D

**Comment by jggoebel** [comment]
Sure i also like it better that way - but that is how it currently works.

**Comment by zackbradys** [comment]
Are you able to share how you are able to use URLs? I haven't found it in the docs, but if you have it working, then it would be great to see! @jggoebel

**Comment by jggoebel** [comment]
@zackbradys 
We just set the URL to an SVG Image Inside the values. Still only supports SVG.

**Comment by clemenko** [comment]
what is holding up the merge?

**Comment by clemenko** [comment]
can we please merge this?

**Comment by clemenko** [comment]
@jggoebel After talking to Eamon I added back the admin.title and admin.favicon values. Would love to see this get merged and a new chart released.

**Pull request merged**
